project/models/user.py
from flask import session
from flask_login import UserMixin, current_user, login_user, logout_user, current_user
from project.utils.encryption import encrypt_string, validate_string
from project import db, login_manager
from sqlalchemy import or_, desc
from datetime import datetime, timedelta
from project import bcrypt
import uuid


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(length=255), nullable=False)
    last_name = db.Column(db.String(length=255), nullable=False)
    display_name = db.Column(db.String(length=255), nullable=False, unique=True)
    email_address = db.Column(db.String(length=255), nullable=False, unique=True)
    email_address_normalized = db.Column(db.String(length=255))
    password_hash = db.Column(db.String(length=255), nullable=False)
    tos_agreed_at = db.Column(db.DateTime, nullable=False)
    password_request_token = db.Column(db.String(length=255), nullable=True)
    password_request_token_expire_at = db.Column(db.DateTime, nullable=True)
    validation_token = db.Column(db.String(length=255), nullable=True)
    created_at = db.Column(db.DateTime, nullable=False)
    modified_at = db.Column(db.DateTime, nullable=False)

    def __init__(self, first_name, last_name, email_address,  password, display_name):
        now = datetime.now()
        
        self.email_address = email_address
        self.first_name = first_name
        self.last_name = last_name
        self.display_name = display_name
        self.tos_agreed_at = datetime.now()
        self.created_at = now
        self.modified_at = now
        self.validation_token = uuid.uuid4().hex

        self.encrypt_password(password)
        email_identifier_domain = self.email_address.split("@")
        email_identifier_filter = email_identifier_domain[0].split("+")
        self.email_address_normalized = "{}@{}".format(email_identifier_filter[0], email_identifier_domain[1])


    def check_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)


    def encrypt_password(self, password):
        self.password_hash = bcrypt.generate_password_hash(password=password)
        self.password_request_token = None
        self.password_request_token_expire_at = None


    def save(self):
        db.session.add(self)
        db.session.commit()


    def update_password_and_save(self, password):
        self.password_hash = bcrypt.generate_password_hash(password=password)
        self.password_request_token = None
        self.password_request_token_expire_at = None
        self.save()


    def user_fullname(self):
        return "{} {}".format(self.first_name, self.last_name)
        

    @staticmethod
    def clear_password_token(email_address):
        user = User.query.filter_by(email_address=email_address).first()
        user.password_request_token = None
        user.password_request_token_expire_at = None
        db.session.add(user)
        db.session.commit()
        return user


    @staticmethod
    def create_user(first_name, last_name, email_address, password, display_name):
        user = User(first_name=first_name, last_name=last_name, email_address=email_address, password=password, display_name=display_name)
        user.save()
        login_user(user)
        return user


    @staticmethod
    def generate_password_reset_token(email_address):
        
        # Get the user by email address
        user = User.query.filter_by(email_address=email_address).first()

        if user != None:
            if (user.password_request_token == None or user.password_request_token == "" or 
               (user != None and (user.password_request_token != "" or user.password_request_token != None) and 
               user.password_request_token_expire_at < datetime.now())):
                token = uuid.uuid4().hex
                user.password_request_token = token
                user.password_request_token_expire_at = '{:%Y-%m-%d %H:%M:%S}'.format(datetime.now() + timedelta(hours=24))
                user.save()

        # Retuen the user object    
        return user


    @staticmethod
    def get_user_by_reset_token(reset_token):
        user = User.query.filter_by(password_request_token=reset_token).first()
        return user


    @staticmethod
    def login_user(email_address, password):
        user = User.query.filter_by(email_address=email_address).first()
        if user != None and user.check_password(password):
            login_user(user)
            return user
        return None


    @staticmethod
    def logout_user():
        logout_user()
        return None


    @staticmethod
    def save_password(email_address, password):
        user = User.query.filter_by(email_address=email_address).first()
        user.encrypt_password(password)
        user.save()
        return user

project/forms/user_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, HiddenField, PasswordField, SelectField, SubmitField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Email, EqualTo 
from project.forms.validators import ProfileUniqueUserEmail, ProfileUniqueUserDisplayName, UniqueUserEmail, UniqueUserDisplayName


__ALL__ = [
 'ForgotPassword',   
 'LoginForm',
 'SignUp'
]


class ForgotPasswordForm(FlaskForm):
    email_address = EmailField('Email Address',validators=[DataRequired(), Email()])
    submit = SubmitField('Log In')


class ForgotPasswordResetForm(FlaskForm):
    email_address = EmailField('Email Address',validators=[DataRequired(), Email()])
    password = PasswordField('Password',validators=[DataRequired()])    
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(),EqualTo('password',message="Passwords do not match")])    
    submit = SubmitField('Log In')


class LoginForm(FlaskForm):
    email_address = EmailField('Email Address',validators=[DataRequired(), Email()])
    password = PasswordField('Password',validators=[DataRequired()])    
    remember = BooleanField('Remember me')    
    submit = SubmitField('Log In')


class ProfileEditForm(FlaskForm):
    first_name = StringField('First Name',validators=[DataRequired()])
    last_name = StringField('Last Name',validators=[DataRequired()])
    display_name = StringField('Display Name',validators=[DataRequired(), ProfileUniqueUserDisplayName("This display name is in use by another account.")])
    email_address = EmailField('Email Address',validators=[DataRequired(), Email(), ProfileUniqueUserEmail("This email address is in use by another account.")])
    submit = SubmitField('Save Profile')


class SignUpForm(FlaskForm):
    first_name = StringField('First Name',validators=[DataRequired()])
    last_name = StringField('Last Name',validators=[DataRequired()])
    display_name = StringField('Display Name',validators=[DataRequired(), UniqueUserDisplayName("This display name is in use by another account.")])
    email_address = EmailField('Email Address',validators=[DataRequired(), Email(), UniqueUserEmail("This email address is in use by another account.")])
    password = PasswordField('Password',validators=[DataRequired()])    
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(),EqualTo('password',message="Passwords do not match")])    
    submit = SubmitField('Register')
    

project/views/core_views.py
from flask import Blueprint, request,  session, render_template, url_for, redirect
from flask_login import current_user

core_views = Blueprint('core_views', __name__)

##############################
# login user page
##############################
@core_views.route('/')
def page_index():
    return render_template('v1/core/index.html')
    
    
@core_views.route('/terms-of-service')
def page_terms_of_service():
    return render_template('v1/core/terms_of_service.html')    


@core_views.route('/welcome')
def page_welcome():
    return render_template('v1/core/welcome.html')    

project/views/user_views.py
from datetime import datetime, timedelta

from flask import Blueprint, request,  session, render_template, url_for, redirect, flash
from flask_login import current_user

from project.forms.user_forms import LoginForm, SignUpForm, ForgotPasswordForm, ProfileEditForm, ForgotPasswordResetForm
from project.models import User
from project.utils.emails import send_password_reset_token
from project.uri_paths import uri_paths

user_views = Blueprint('user_views', __name__)

##############################
# User register
##############################
@user_views.route(uri_paths['user_signup'], methods=['GET','POST'])
def page_register():

    form = SignUpForm()

    if form.validate_on_submit():
        user = User.create_user(form.first_name.data, form.last_name.data, form.email_address.data,
                                form.password.data, form.display_name.data);
        return redirect(url_for('core_views.page_welcome'))

    return render_template('v1/user/sign-up.html', form=form)
    

##############################
# User Login
##############################
@user_views.route(uri_paths['user_login'], methods=['GET','POST'])
def page_login():
    
    form = LoginForm()
    if form.validate_on_submit():
        authentication = User.login_user(form.email_address.data, form.password.data)
        if authentication != None:
            return redirect(url_for('core_views.page_welcome'))
        else:
            flash("Invalid email address or password.  Please try again.", 'danger')
    
    return render_template('v1/user/log-in.html', form=form)
    

##############################
# User Login
##############################
@user_views.route(uri_paths['user_logout'], methods=['GET'])
def page_logout():
    User.logout_user()
    return redirect(url_for('core_views.page_index'))
    

##############################
# User Profile
##############################
@user_views.route(uri_paths['user_profile'], methods=['GET'])
def page_profile():
    return render_template('v1/user/profile.html')
    

##############################
# Edit User Profile
##############################
@user_views.route(uri_paths['user_profile_edit'], methods=['GET', 'POST'])
def page_profile_edit():
    
    form = ProfileEditForm()

    if request.method != "POST":
        form.email_address.data = current_user.email_address
        form.display_name.data = current_user.display_name
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name

    if form.validate_on_submit():
        current_user.email_address = form.email_address.data
        current_user.display_name = form.display_name.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.save()
        
        flash('Profile updated.', 'success')
        return redirect(url_for('user_views.page_profile'))
        
    
    return render_template('v1/user/profile_edit.html', form=form)
    

##############################
# User Password Forget
##############################
@user_views.route(uri_paths['user_forgot_password'], methods=['GET','POST'])
def page_forgot_password():

    user = None
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        user = User.generate_password_reset_token(form.email_address.data)
        
        if user != None:
            send_password_reset_token(user.email_address, user.password_request_token)
            return redirect(url_for('user_views.page_forgot_password_request_processed'))
        else:
            flash('We can not find a user with that email address please try again.', 'danger')
    
    return render_template('v1/user/forgot-password.html', form=form, user=user)
    

##############################
# User Password Forget Processed
##############################
@user_views.route(uri_paths['user_forgot_password_processed'], methods=['GET','POST'])
def page_forgot_password_request_processed():
    return render_template('v1/user/forgot-password-processed.html')
    

##############################
# User Password Reset with Token
##############################
@user_views.route(uri_paths['user_password_reset_with_token'], methods=['GET','POST'])
def page_password_reset_with_token(reset_token):
    user = User.get_user_by_reset_token(reset_token);
    if user is None or user.password_request_token_expire_at is None:
        return render_template('v1/user/forgot-password-reset-token-invalid.html')
    elif user.password_request_token_expire_at < datetime.now():
        return render_template('v1/user/forgot-password-reset-token-expired.html')

    form = ForgotPasswordResetForm()
    
    if form.validate_on_submit():
        user.update_password_and_save(form.password.data)

        flash('Your password has been reset, please log in.', 'info')
        return redirect(url_for('user_views.page_login'))
    
    return render_template('v1/user/forgot-password-reset.html', form=form)
    

##############################
# User email address check
##############################
@user_views.route('/api/common/unique-email/<email_address>', methods=['POST'])
def page_api_unique_email(email_address):
    return False


##############################
# User display name check
##############################
@user_views.route('/api/common/unique-display-name/<display_name>', methods=['POST'])
def page_api_unique_display_name(display_name):
    return False

project/templates/v1/user/forgot-password-processed.html
{% extends 'v1/base/main.html' %}
{% from "v1/helpers/_formhelpers.html" import render_field_with_placeholder, render_form_errors %}

{% block page_styles %}
<style type="text/css">
  .colorgraph {
    height: 5px;
    border-top: 0;
    background: #c4e17f;
    border-radius: 5px;
    background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  }
</style>
{% endblock %}

{% block page_content %}
<div class="container">
  <div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3">
      Your reset token will be emailed to you, maybe...
  	</div>
  </div>
</div>
{% endblock %}

project/templates/v1/user/forgot-password-reset-token-expired.html
{% extends 'v1/base/main.html' %}

{% block page_styles %}
<style type="text/css">
  .colorgraph {
    height: 5px;
    border-top: 0;
    background: #c4e17f;
    border-radius: 5px;
    background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  }
</style>
{% endblock %}

{% block page_content %}
<div class="container">
  <div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3">
      Your existing token is expired, please request another one.
  	</div>
  </div>
</div>
{% endblock %}

project/templates/v1/user/log-in.html
{% extends 'v1/base/main.html' %}
{% from "v1/helpers/_flashedhelpers.html" import flashed_message_basic %}
{% from "v1/helpers/_formhelpers.html" import render_field_with_placeholder, render_form_errors %}


{% block page_styles %}
<style type="text/css">
  .colorgraph {
    height: 5px;
    border-top: 0;
    background: #c4e17f;
    border-radius: 5px;
    background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  }
</style>
{% endblock %}

{% block page_content %}
<div class="container">
  <div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3">

      {% for message in get_flashed_messages(with_categories=true) %}
      {{ flashed_message_basic(message) }}
      {% endfor %}
      
  		<form role="form" novalidate method="POST">
        {{ form.hidden_tag() }}
          <fieldset>
  				<h2>Please Sign In</h2>
  				<hr class="colorgraph">
  				<div class="form-group">
            {{ render_field_with_placeholder(form.email_address, tabindex="1") }}
  				</div>
  				<div class="form-group">
            {{ render_field_with_placeholder(form.password, tabindex="1") }}
  				</div>
  				<span class="button-checkbox">
            <!-- <button type="button" class="btn" data-color="info">Remember Me</button>
                      <input type="checkbox" name="remember_me" id="remember_me" checked="checked" class="hidden">
            <a href="{{ url_for('user_views.page_forgot_password') }}" class="btn btn-link pull-right">Forgot Password?</a> -->
  				</span>
    			<div class="row">
    				<div class="col-xs-12 col-sm-12 col-md-12">
    					 <a href="{{ url_for('user_views.page_forgot_password') }}">Forgot Password</a>
    				</div>
    			</div>
  				<hr class="colorgraph">
  				<div class="row">
  					<div class="col-xs-6 col-sm-6 col-md-6">
              <input type="submit" class="btn btn-lg btn-success btn-block" value="Sign In">
  					</div>
  				</div>
  			</fieldset>
  		</form>
  	</div>
  </div>
</div>
{% endblock %}

project/templates/v1/user/profile.html
{% extends 'v1/base/main.html' %}
{% from "v1/helpers/_flashedhelpers.html" import flashed_message_basic %}

{% block page_content %}
<div class="container">
  <div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3">
      {% for message in get_flashed_messages(with_categories=true) %}
      {{ flashed_message_basic(message) }}
      {% endfor %}
      
      Profile ( <a href="{{ url_for('user_views.page_profile_edit') }}">Edit</a>)
      
      <table class="table">
        <tr>
          <td>Email Address</td>
          <td>{{ current_user.email_address }}</td>
        </tr>
        <tr>
          <td>First Name</td>
          <td>{{ current_user.first_name }}</td>
        </tr>
        <tr>
          <td>Last Name</td>
          <td>{{ current_user.last_name }}</td>
        </tr>
        <tr>
          <td>Display Name</td>
          <td>{{ current_user.display_name }}</td>
        </tr>
        <tr>
          <td>Password</td>
          <td>************</td>
        </tr>
      </table>
      
  	</div>
  </div>
</div>
{% endblock %}

project/templates/v1/user/sign-up.html
{% extends 'v1/base/main.html' %}
{% from "v1/helpers/_formhelpers.html" import render_field_with_placeholder, render_form_errors %}

{% block page_styles %}
<style type="text/css">
  .colorgraph {
    height: 5px;
    border-top: 0;
    background: #c4e17f;
    border-radius: 5px;
    background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  }
</style>
{% endblock %}

{% block page_content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3">
  		<form role="form" novalidate method="POST">
        {{ form.hidden_tag() }}
  			<h2>Please Sign Up <!-- small>It's free and always will be.</small --></h2>
  			<hr class="colorgraph">
  			<div class="row">
  				<div class="col-xs-12 col-sm-6 col-md-6">
            {{ render_field_with_placeholder(form.first_name, tabindex="1") }}
  				</div>
  				<div class="col-xs-12 col-sm-6 col-md-6">
            {{ render_field_with_placeholder(form.last_name, tabindex="2") }}
  				</div>
  			</div>
        {{ render_field_with_placeholder(form.display_name, tabindex="3") }}
        {{ render_field_with_placeholder(form.email_address, tabindex="4") }}
  			<div class="row">
  				<div class="col-xs-12 col-sm-6 col-md-6">
            {{ render_field_with_placeholder(form.password, tabindex="5") }}
  				</div>
  				<div class="col-xs-12 col-sm-6 col-md-6">
            {{ render_field_with_placeholder(form.confirm_password, tabindex="6") }}
  				</div>
  			</div>
  			<div class="row">
  				<div class="col-xs-12 col-sm-12 col-md-12">
  					 By clicking <strong class="label label-primary">Register</strong>, you agree to the <a href="{{ url_for('core_views.page_terms_of_service') }}" adata-toggle="modal" adata-target="#t_and_c_m">Terms and Conditions</a> set out by this site, including our Cookie Use.
  				</div>
  			</div>
			
  			<hr class="colorgraph">
  			<div class="row">
  				<div class="col-xs-12 col-md-6"><input type="submit" value="Register" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
  			</div>
  		</form>
  	</div>
  </div>
</div>

{% endblock %}